# Generated by Django 5.2.1 on 2025-07-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_perfil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, default='perfil/foto-padrao.png', upload_to='perfil/foto/'),
        ),
    ]
