# Generated by Django 5.2.1 on 2025-07-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_alter_perfil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(default='perfil/foto/foto-padrao.jpg', upload_to='perfil/foto/'),
        ),
    ]
