# Generated by Django 5.2.1 on 2025-07-06 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
