# Generated by Django 5.2.1 on 2025-07-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_myuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='force_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
