# Generated by Django 5.2.1 on 2025-07-06 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blocos',
            options={'ordering': ['id'], 'verbose_name': '3 - Blocos', 'verbose_name_plural': '3 - Blocos'},
        ),
    ]
