# Generated by Django 5.2.1 on 2025-07-02 04:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagemforum',
            name='data_publicacao',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
