# Generated by Django 5.2.1 on 2025-07-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_postagemforum_data_publicacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postagemforum',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Postagem Forum', 'verbose_name_plural': 'Postagens Forum'},
        ),
        migrations.AlterField(
            model_name='postagemforum',
            name='data_publicacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
