# Generated by Django 5.2.1 on 2025-07-08 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_postagemforum_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postagemforum',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Postagem Forum', 'verbose_name_plural': 'Postagem Forum'},
        ),
        migrations.CreateModel(
            name='PostagemForumImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(upload_to='postagem-forum/', verbose_name='Imagem Anexo')),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postagem_imagens', to='forum.postagemforum')),
            ],
        ),
    ]
